-d C:\Users\serve\OneDrive\Belgeler\fpga_project_3\impl\gwsynthesis\fpga_project_3.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\serve\OneDrive\Belgeler\fpga_project_3\src\fpga_project_3.cst
-cfg C:\Users\serve\OneDrive\Belgeler\fpga_project_3\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
